### ISSUE TITLE
unreachable code issue

### ISSUE THREAD

**Issue by ghost** [Luukdegram/lemon#2]
It seems as if there is an issue building https://github.com/Luukdegram/lemon/blob/master/src/object.zig#L137-L182

trying to do so gives 
```
C:\Users\infrandomness\Documents\Dev\Zig\lemon\src\object.zig:141:9: error: unreachable code
        const kind = kindToString(self.kind);
        ^
C:\Users\infrandomness\Documents\Dev\Zig\lemon\src\object.zig:140:9: note: control flow is diverted here
        @compileError("TODO implement when zlib compression is supported");
        ^
```

This seems related to https://github.com/ziglang/zig/issues/8631

However, it also looks [std.compress.zlig](https://github.com/ziglang/zig/blob/master/lib/std/compress/zlib.zig) doesn't contain any function to compress data.

What would be the right way to fix this problem?

**Comment by Luukdegram** [comment]
The compileError could be replaced with a `@panic()` for now. Unfortunately, std still doesn't have any zlib compression. Seems nobody is really interested into creating a PR for it. It's pretty much a requirement to create any object for Git though.

**Comment by ghost** [comment]
`@panic()` still leads to the same error as I'm currently getting

(Sorry for the unintentional ping)

**Comment by ghost** [comment]
I was also thinking, for the time being, would it be worth leveraging the [C API](https://zlib.net/) ?

**Comment by Luukdegram** [comment]
> I was also thinking, for the time being, would it be worth leveraging the [C API](https://zlib.net/) ?

Sure! The library is small enough to rely on it for now, and since it's a small part of the library we can easily swap it at a later point. As regards to the error you're getting I'll take a look tomorrow.

**Comment by ghost** [comment]
I'm also not really sure how I should compress an object in ram with zlib, the code for it also appears to be already present, do I need to compress the buffer in object.zig#encode()?

**Comment by Luukdegram** [comment]
> I'm also not really sure how I should compress an object in ram with zlib, the code for it also appears to be already present, do I need to compress the buffer in object.zig#encode()?

First off, replacing `@compileError()` with `std.debug.panic()` works to work around this control flow issue.
To be honest, `encode` should probably be rewritten as it contains quite a few mistakes. But the idea is that you indeed compress the contents of `buffer`. Note that the sha1 hash must be calculated on the original data, not on the compressed data.
